[package]
name = "crypto"
version = "0.1.0"
authors = ["The Attestation Agent Authors"]
publish = false
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.1", optional = true }
anyhow.workspace = true
base64.workspace = true
openssl = { version = "0.10", features = ["vendored"], optional = true}
ctr = { version = "0.9.2", optional = true }
rand = { version = "0.8.5" }
rsa = "0.9.2"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum = { workspace = true, features = [ "derive" ] }
zeroize.workspace = true

[dev-dependencies]
rstest.workspace = true

[features]
default = ["rust-crypto"]
rust-crypto = ["dep:aes-gcm", "ctr"]
openssl = ["dep:openssl"]